package com.invoiceme.invoices.createinvoice;

import com.invoiceme.domain.common.DiscountType;
import com.invoiceme.domain.common.InvoiceNumber;
import com.invoiceme.domain.common.Money;
import com.invoiceme.domain.invoice.LineItem;
import com.invoiceme.invoices.shared.InvoiceDto;
import com.invoiceme.invoices.shared.LineItemRequestDto;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface CreateInvoiceMapper {
    
    @Mapping(target = "invoiceNumber", ignore = true) // Generated by handler
    @Mapping(target = "lineItems", expression = "java(toLineItems(request.getLineItems()))")
    CreateInvoiceCommand requestToCommand(CreateInvoiceRequest request);
    
    InvoiceDto toDto(com.invoiceme.domain.invoice.Invoice invoice);
    
    default String map(InvoiceNumber invoiceNumber) {
        return invoiceNumber == null ? null : invoiceNumber.getValue();
    }
    
    default List<LineItem> toLineItems(List<LineItemRequestDto> dtos) {
        if (dtos == null) {
            return null;
        }
        java.util.List<LineItem> items = new java.util.ArrayList<>();
        for (int i = 0; i < dtos.size(); i++) {
            LineItemRequestDto dto = dtos.get(i);
            items.add(LineItem.create(
                dto.getDescription(),
                dto.getQuantity(),
                Money.of(dto.getUnitPrice()),
                dto.getDiscountType() != null ? dto.getDiscountType() : DiscountType.NONE,
                dto.getDiscountValue() != null ? Money.of(dto.getDiscountValue()) : Money.zero(),
                dto.getTaxRate() != null ? dto.getTaxRate() : java.math.BigDecimal.ZERO,
                i
            ));
        }
        return items;
    }
}

